server:
  port: 12345

spring:
  #  devtools: #热部署配置
  #    restart:
  #      enabled: true  #设置开启热部署
  #      additional-paths: src/main/java  #重启目录

  datasource:
    url: jdbc:mysql://localhost:3306/base_user?serverTimezone=Hongkong&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwertyuiop123.


mybatis:
  mapper-locations: classpath:mapper/*.xml